"""Typed application tables and record validation; no service dependencies."""

from __future__ import annotations

import math
from datetime import date

from core.services.application_schema import TableDefinition
from fastapi import HTTPException
from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    func,
)

_TYPES = {
    "text": String,
    "integer": Integer,
    "number": Float,
    "boolean": Boolean,
    "date": Date,
    "json": JSON,
}


def sql_table(app_id: str, definition: TableDefinition) -> Table:
    """Opaque application prefix is generated by the server, never supplied SQL."""
    if len(app_id) != 32 or any(c not in "0123456789abcdef" for c in app_id):
        raise HTTPException(404, "Application not found")
    columns = [
        Column("id", String(32), primary_key=True),
        Column("version", Integer, nullable=False),
        Column("created_at", DateTime(timezone=True), nullable=False),
    ]
    for field in definition.columns:
        sql_type = String(field.max_length) if field.type == "text" else _TYPES[field.type]()
        columns.append(
            Column(
                field.name,
                sql_type,
                nullable=not field.required,
                unique=field.unique,
                index=field.indexed,
            )
        )
        if field.type == "text":
            columns.append(
                CheckConstraint(
                    func.length(Column(field.name)) <= field.max_length,
                    name=f"length_{field.name}",
                )
            )
    return Table(f"app_{app_id}_{definition.name}", MetaData(), *columns)


def table_definition(app: dict, name: str) -> TableDefinition:
    definition = (app["tables"] or {}).get(name)
    if not definition:
        raise HTTPException(404, "Table not found")
    return TableDefinition.model_validate(definition)


def validated_row(definition: TableDefinition, payload: dict, *, partial=False) -> dict:
    fields = {c.name: c for c in definition.columns}
    if set(payload) - set(fields):
        raise HTTPException(422, "Unknown or reserved fields")
    if not partial and any(c.required and payload.get(c.name) is None for c in fields.values()):
        raise HTTPException(422, "Required fields are missing")
    result = {}
    for name, value in payload.items():
        field = fields[name]
        if value is None:
            if field.required:
                raise HTTPException(422, f"{name} is required")
        elif field.type == "text":
            if not isinstance(value, str) or len(value) > field.max_length:
                raise HTTPException(
                    422, f"{name} must be text of at most {field.max_length} characters"
                )
        elif field.type == "integer":
            if type(value) is not int or not -(2**31) <= value < 2**31:
                raise HTTPException(422, f"{name} must be a 32-bit integer")
        elif field.type == "number":
            try:
                finite = type(value) in (float, int) and math.isfinite(value)
            except OverflowError:
                finite = False
            if not finite:
                raise HTTPException(422, f"{name} must be a finite number")
        elif field.type == "boolean":
            if type(value) is not bool:
                raise HTTPException(422, f"{name} must be boolean")
        elif field.type == "json":
            import json

            try:
                if not isinstance(value, (dict, list)):
                    raise ValueError()
                if len(json.dumps(value, allow_nan=False).encode()) > 16384:
                    raise ValueError()
            except (ValueError, TypeError):
                raise HTTPException(422, f"{name} must be a bounded JSON object or array")
        elif field.type == "date":
            try:
                value = date.fromisoformat(value)
            except (ValueError, TypeError):
                raise HTTPException(422, f"{name} must be an ISO date")
        result[name] = value
    return result


def json_record(row) -> dict:
    return {k: v.isoformat() if hasattr(v, "isoformat") else v for k, v in dict(row).items()}
