/** Ant Design theme tokens aligned with UI design spec — a single shared point for main.tsx (including the CE overlay version). */
export const appTheme = {
  token: {
    colorPrimary: '#126DFF',
    colorSuccess: '#02B589',
    colorWarning: '#F8AB42',
    colorError: '#FC5D5D',
    colorInfo: '#126DFF',
    colorText: '#101828',
    colorTextSecondary: '#475467',
    colorTextTertiary: '#667085',
    colorTextQuaternary: '#98A2B3',
    colorBorder: '#DDE3EC',
    colorBorderSecondary: '#E9EDF3',
    colorBgContainer: '#FFFFFF',
    colorBgLayout: '#F5F7FB',
    borderRadius: 10,
    borderRadiusLG: 16,
    borderRadiusSM: 6,
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei UI", "Microsoft YaHei", sans-serif',
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
  },
};
